### ISSUE TITLE
CRA 평가

### ISSUE THREAD

**Issue by SJin-Choi** [hmi-jeon/ssd-cli#112]
안녕하세요. 
민코딩의 SSD project를 진행한 최세진 강사입니다.

팀장 평가로 Best 팀원 2명을 선발이 필요하여 이곳에 연락 남깁니다.

팀장님께서는 
**sejin.choi@mincoding.co.kr**
로 Best 팀원 2명에 대한 명단을 제출 부탁드립니다.

감사합니다.

**Comment by hmi-jeon** [comment]
@SJin-Choi 
안녕하세요. 강사님.

메일 송부드렸습니다.
감사합니다.
